name: GHA Pipeline
on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: LT Username
      accessKey:
        description: LT Access Key
        required: true

env:
    NODE_VERSION: 16
jobs:
  executeE2eTests:
    name: Execute E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@main

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Starting CLI testing
        shell: bash
        run: |
              curl https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute -o hyperexecute
              chmod u+x hyperexecute
              ./hyperexecute --user ${{ github.event.inputs.username }} --key ${{ github.event.inputs.accessKey }} --config yaml/win/cucumber_hyperexecute_matrix_sample.yaml 
